import { buildSchemeSearch } from './SchemeUrlState';

export const SHARE_TEXT = 'Check out my terminal color scheme generated by the 4bit Terminal Color Scheme Designer.';
const SHARE_BASE_URL = 'https://ciembor.github.io/4bit/';

export function buildShareUrl(scheme, location = null) {
  const origin = location?.origin || 'https://ciembor.github.io';
  const pathname = location?.pathname || '/4bit/';

  return `${origin}${pathname}${buildSchemeSearch(scheme)}`;
}

export function buildTwitterShareHref(scheme, location = null) {
  const params = new URLSearchParams({
    text: SHARE_TEXT,
    url: buildShareUrl(scheme, location),
    via: 'ciembor',
  });

  return `https://twitter.com/intent/tweet?${params.toString()}`;
}

export function defaultShareBaseUrl() {
  return SHARE_BASE_URL;
}
